create sequence NNEWSMA.SEQ_NEWS
/

create table NNEWSMA.NEWS
(
    ID                  NUMBER(15)      not null
        constraint PK_NEWS
            primary key,
    TITEL               NVARCHAR2(1024) not null,
    CONTENT             NCLOB           not null,
    VEROEFFENTLICHTDATE TIMESTAMP(6),
    KONTAKTNAME         NVARCHAR2(512),
    KONTAKTFIRMA        NVARCHAR2(512),
    KONTAKTTEL          NVARCHAR2(512),
    KONTAKTEMAIL        NVARCHAR2(512),
    KONTAKTPOS          NVARCHAR2(512),
    KONTAKTUID          NVARCHAR2(255),
    LASTCHANGEDATE      TIMESTAMP(6)    not null,
    LASTCHANGEUSER      NVARCHAR2(255)  not null,
    VORSCHAUDOKID       NUMBER(15),
    GUELTIGVON          TIMESTAMP(6),
    GUELTIGBIS          TIMESTAMP(6),
    KONTAKTABTEILUNG    NVARCHAR2(512),
    DELETED             NUMBER(1) default 0,
    AUTOPUBNOTIFY       NUMBER(1) default 1,
    FIRSTPUBLISHED      TIMESTAMP(6),
    ORIGINALCREATORUID  NVARCHAR2(255)  not null
)
/

INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (1, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:17.252070', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');
INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (2, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:19.735427', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');
INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (3, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:20.828624', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');
INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (4, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:22.004186', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');
INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (5, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:23.002648', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');
INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (6, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:23.972853', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');
INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (7, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:24.983648', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');
INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (8, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:25.974360', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');
INSERT INTO NNEWSMA.NEWS (ID, TITEL, CONTENT, VEROEFFENTLICHTDATE, KONTAKTNAME, KONTAKTFIRMA, KONTAKTTEL, KONTAKTEMAIL, KONTAKTPOS, KONTAKTUID, LASTCHANGEDATE, LASTCHANGEUSER, VORSCHAUDOKID, GUELTIGVON, GUELTIGBIS, KONTAKTABTEILUNG, DELETED, AUTOPUBNOTIFY, FIRSTPUBLISHED, ORIGINALCREATORUID) VALUES (9, 'Lorem Ipsum ABC', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', null, null, null, null, null, null, null, TIMESTAMP '2024-11-25 07:22:26.940037', 'userid', null, null, null, null, 0, 1, CURRENT_TIMESTAMP, 'userid');

